# Generated by Django 4.2.2 on 2023-06-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_alter_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyprice',
            name='volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
